Bug 1891121 - Add experiment brief links to experiment and rollout tables
mozilla/skylight pull request #524
Opened 2024-12-18 21:52 UTC by sarahhjchung

[Bug 1891121](https://bugzilla.mozilla.org/show_bug.cgi?id=1891121)

Changes made:
- `RecipeInfo` now includes an `experimentBriefLink` property with the url to experiment link Google docs
- A tooltip button of the `FileText` icon from lucide-icons is now displayed next to the experiment/rollout name if an experiment brief link exists

2024-12-18 21:58 UTC, sarahhjchung commented
`DocumentationLinks` were exposed in the experimenter v7 api and I am able to get the data from it. However, I'm getting build failures due to `documentationLinks` not being defined in the `node_modules/@mozilla/nimbus-shared/types/experiments.ts` file. Is this file something that needs to be updated by us or something we need to request the nimbus team for?

2024-12-19 16:29 UTC, dmose commented
We need to request that the experimenter team do it (or put in a PR ourselves and ask for their review).

2025-03-21 19:59 UTC, dmose requested changes
This is looking good!  A couple of UX things that I think we want to tweak though:

![image](https://github.com/user-attachments/assets/3303cb22-84bc-47d7-9014-7a225946f85f)

1. In all of them, I think the experiment slug wants to be indented to start in the same place as the human-readable experiment name, as it's visually a bit confusing as-is.  That said, that would line the experiment info up with the branch info, so maybe we'd want to indent the branches more too. Play around a bit and see what looks reasonable.
2. In the Mozilla VPN one, if it's easy to prevent wrapping (eg with `&nbsp;`) a line-break just before the symbol, I think the visual presentation would be smoother.

2025-03-21 19:59 UTC, dmose commented on app/columns.tsx
> +                  <path d="m1.71278 0h.57093c.31531 0 .57092.255837.57092.571429 0 .315591-.25561.571431-.57092.571431h-.57093c-.31531 0-.57093.25583-.57093.57143v4.57142c0 .3156.25562.57143.57093.57
Can you add an XXX comment both here and later in the file that we should switch to the Lucide Icon for an external link instead of maintaining our own? (I don't think we need to fix this now).

2025-03-21 19:59 UTC, dmose commented on package.json
>      "@mozilla/nimbus-shared": "^2.5.2",
From reading https://github.com/mozilla/nimbus-shared, it sounds like we don't need `nimbus-shared` any more.

2025-03-21 19:59 UTC, dmose commented on lib/nimbusRecipe.ts
> +  typeof nimbusExperimentV7Schema.properties.documentationLinks;
I think it would be helpful to put JSDoc comments here explaining why you're doing the type aliasing.

2025-03-24 20:40 UTC, sarahhjchung commented
I played around with the spacing and indenting and concluded on this. 

<img width="1337" alt="Screenshot 2025-03-24 at 4 39 39 PM" src="https://github.com/user-attachments/assets/983a7f17-33f3-451d-a243-c2840abf9cce" />

I've made the user facing name experiment/rollout (ie. the bold text) to have the `overflow-visible` property to prevent weird wrapping with the external link icon because I couldn't figure out exactly how to work `&nbsp;` to my advantage. Let me know if the UI tweaks look good and I'm always welcome to more feedback!

2025-04-03 20:33 UTC, dmose approved these changes
This looks good to me.  One small question to answer and/or address; I don't need to see this again.  Thanks for making this happen as well as your patience! r=dmose

2025-04-03 20:33 UTC, dmose commented on lib/messageUtils.ts
> +    menu_message: {
There are two different names for the same surface?

2025-04-03 20:46 UTC, merged